apiVersion: v1
kind: Pod
metadata:
  name: k8s
  namespace: k8s-example
spec:
  containers:
  - name: cpu-demo-ctr
    image: k8s-test
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
