apiVersion: v1
kind: Pod
metadata:
  name: k8s
spec:
  containers:
  - name: k8s-demo-ctr
    image: guspetv/k8s-test
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
